CREATE TABLE KATEGORIE
  (
    id      NUMBER NOT NULL ,
    druh    VARCHAR2 (50) NOT NULL ,
    semestr VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE KATEGORIE ADD CONSTRAINT KATEGORIE_PK PRIMARY KEY ( id ) ;


CREATE TABLE PREDMET
  (
    id              NUMBER NOT NULL ,
    nazev           VARCHAR2 (100) NOT NULL ,
    popis           VARCHAR2 (255) ,
    pozadavky       VARCHAR2 (255) NOT NULL ,
    zpusobZakonceni VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE PREDMET ADD CONSTRAINT PREDMET_PK PRIMARY KEY ( id ) ;


CREATE TABLE REL_RA_UCEBNA
  (
    ROZVRHOVA_AKCE_id NUMBER NOT NULL ,
    UCEBNA_id         NUMBER NOT NULL
  ) ;
ALTER TABLE REL_RA_UCEBNA ADD CONSTRAINT REL_RA_UCEBNA_PK PRIMARY KEY ( ROZVRHOVA_AKCE_id, UCEBNA_id ) ;


CREATE TABLE ROZVRHOVA_AKCE
  (
    id            NUMBER NOT NULL ,
    cas           TIMESTAMP NOT NULL ,
    datum         DATE NOT NULL ,
    pocetHodin    NUMBER NOT NULL CHECK (pocetHodin > 0) ,
    UCITEL_id     NUMBER NOT NULL ,
    KATEGORIE_id  NUMBER NOT NULL ,
    PREDMET_id    NUMBER NOT NULL ,
    pocetStudentu NUMBER NOT NULL CHECK (pocetStudentu > 0)
  ) ;
ALTER TABLE ROZVRHOVA_AKCE ADD CONSTRAINT ROZVRHOVA_AKCE_PK PRIMARY KEY ( id ) ;


CREATE TABLE UCEBNA
  (
    id        NUMBER NOT NULL ,
    kapacita  NUMBER NOT NULL CHECK (kapacita > 0),
    nazev     VARCHAR2 (100) NOT NULL ,
    budova    CHAR (15) NOT NULL ,
    laborator CHAR (1)
  ) ;
ALTER TABLE UCEBNA ADD CONSTRAINT UCEBNA_PK PRIMARY KEY ( id ) ;


CREATE TABLE UCITEL
  (
    id        NUMBER NOT NULL ,
    jmeno     VARCHAR2 (100) NOT NULL ,
    prijmeni  VARCHAR2 (100) NOT NULL ,
    telefon   NUMBER NOT NULL ,
    fakulta   VARCHAR2 (255) NOT NULL ,
    titulPred CHAR (15) ,
    titulZa   CHAR (15)
  ) ;
ALTER TABLE UCITEL ADD CONSTRAINT UCITEL_PK PRIMARY KEY ( id ) ;


ALTER TABLE REL_RA_UCEBNA ADD CONSTRAINT FK_ASS_3 FOREIGN KEY ( ROZVRHOVA_AKCE_id ) REFERENCES ROZVRHOVA_AKCE ( id ) ;

ALTER TABLE REL_RA_UCEBNA ADD CONSTRAINT FK_ASS_4 FOREIGN KEY ( UCEBNA_id ) REFERENCES UCEBNA ( id ) ;

ALTER TABLE ROZVRHOVA_AKCE ADD CONSTRAINT ROZVRHOVA_AKCE_KATEGORIE_FK FOREIGN KEY ( KATEGORIE_id ) REFERENCES KATEGORIE ( id ) ;

ALTER TABLE ROZVRHOVA_AKCE ADD CONSTRAINT ROZVRHOVA_AKCE_PREDMET_FK FOREIGN KEY ( PREDMET_id ) REFERENCES PREDMET ( id ) ;

ALTER TABLE ROZVRHOVA_AKCE ADD CONSTRAINT ROZVRHOVA_AKCE_UCITEL_FK FOREIGN KEY ( UCITEL_id ) REFERENCES UCITEL ( id ) ;

CREATE SEQUENCE KATEGORIE_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE PREDMET_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE ROZVRHOVA_AKCE_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE UCEBNA_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE UCITEL_id_SEQ START WITH 1 NOCACHE ORDER ;
