SET AUTOTRACE ON;
SET ECHO ON;
-- Porušení triviálních integritiních omezení tabulky UCITEL
INSERT INTO UCITEL (ID, JMENO, PRIJMENI, TELEFON, FAKULTA, TITULPRED, TITULZA) VALUES (1, 'John', 'Brown', 355370637, 'jm3l7K', NULL, NULL);
INSERT INTO UCITEL (ID, JMENO, PRIJMENI, TELEFON, FAKULTA, TITULPRED, TITULZA) VALUES (UCITEL_id_SEQ. nextval, NULL, 'Brown', 355370637, 'jm3l7K', NULL, NULL);
INSERT INTO UCITEL (ID, JMENO, PRIJMENI, TELEFON, FAKULTA, TITULPRED, TITULZA) VALUES (UCITEL_id_SEQ. nextval, 'John', NULL, 355370637, 'jm3l7K', NULL, NULL);
INSERT INTO UCITEL (ID, JMENO, PRIJMENI, TELEFON, FAKULTA, TITULPRED, TITULZA) VALUES (UCITEL_id_SEQ. nextval, 'John', 'Brown', NULL, 'jm3l7K', NULL, NULL);
INSERT INTO UCITEL (ID, JMENO, PRIJMENI, TELEFON, FAKULTA, TITULPRED, TITULZA) VALUES (UCITEL_id_SEQ. nextval, 'John', 'Brown', 355370637, NULL, NULL, NULL);

-- Porušení triviálních integritiních omezení tabulky KATEGORIE
INSERT INTO KATEGORIE (ID, DRUH, SEMESTR) VALUES (1, '8p6VAAGrY2nO5Kf4iK', 'Zimní');
INSERT INTO KATEGORIE (ID, DRUH, SEMESTR) VALUES (KATEGORIE_id_SEQ.nextval, NULL, 'Letní');
INSERT INTO KATEGORIE (ID, DRUH, SEMESTR) VALUES (KATEGORIE_id_SEQ.nextval, 'v4KJuqpsr5P8', NULL);
INSERT INTO KATEGORIE (ID, DRUH, SEMESTR) VALUES (KATEGORIE_id_SEQ.nextval, 'GUgk0sulIEDAbUtV5kM', 'Jarní');

-- Porušení triviálních integritiních omezení tabulky ROZVRHOVA_AKCE
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (1, TO_TIMESTAMP('8:15:46', 'HH24:MI:SS'), TO_DATE('10.2.21', 'DD.MM.YY'), 2, 101 , 111, 22, 12);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, NULL, TO_DATE('7.9.21', 'DD.MM.YY'), 2, 184 , 169, 15, 11);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('1:44:11', 'HH24:MI:SS'), TO_DATE('15.7.21', 'DD.MM.YY'), 1, 55 , 79, 37, 29);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('9:8:21', 'HH24:MI:SS'), TO_DATE('21.4.21', 'DD.MM.YY'), NULL, 178 , 144, 59, 8);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('11:49:9', 'HH24:MI:SS'), TO_DATE('12.8.21', 'DD.MM.YY'), -1, 164 , 85, 74, 29);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('7:54:33', 'HH24:MI:SS'), TO_DATE('27.3.21', 'DD.MM.YY'), 1, 50 , 14, 77, NULL);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('16:1:50', 'HH24:MI:SS'), TO_DATE('18.3.21', 'DD.MM.YY'), 1, 25 , 174, 54, -1);

-- Porušení triviálních integritiních omezení tabulky PREDMET
INSERT INTO PREDMET (ID, NAZEV, POPIS, POZADAVKY, ZPUSOBZAKONCENI) VALUES (1, 'K7', NULL, 'wfl', 'Zápočet');
INSERT INTO PREDMET (ID, NAZEV, POPIS, POZADAVKY, ZPUSOBZAKONCENI) VALUES (PREDMET_id_SEQ.nextval, NULL, 'GO8YXVfGwm6rs5rPZBO0w2qFSvVRVYGK5op5XIDRC563upLbm9RxJ8H3aPmvK27WQvPaZRDtIm3XIoCzhZmI2qV0ifa6aLqlj0OqKatYgo17Q', 'scdsn7H5oXHBfYeA3', 'Zápočet');
INSERT INTO PREDMET (ID, NAZEV, POPIS, POZADAVKY, ZPUSOBZAKONCENI) VALUES (PREDMET_id_SEQ.nextval, 'rnCW4D', NULL, NULL, 'Zkouška');
INSERT INTO PREDMET (ID, NAZEV, POPIS, POZADAVKY, ZPUSOBZAKONCENI) VALUES (PREDMET_id_SEQ.nextval, 'k0ACam0T0', 'evac', 'qSdMBlNGWzQQx4xwPURGu9hk', NULL);
INSERT INTO PREDMET (ID, NAZEV, POPIS, POZADAVKY, ZPUSOBZAKONCENI) VALUES (PREDMET_id_SEQ.nextval, 'k0ACam0T0', 'evac', 'qSdMBlNGWzQQx4xwPURGu9hk', 'Za docházku');

-- Porušení triviálních integritiních omezení tabulky UCEBNA
INSERT INTO UCEBNA (ID, KAPACITA, NAZEV, BUDOVA, LABORATOR) VALUES (1, 5, 'ni5hzONVl', 'OribTQpxM', 1);
INSERT INTO UCEBNA (ID, KAPACITA, NAZEV, BUDOVA, LABORATOR) VALUES (UCEBNA_id_SEQ.nextval, 32, NULL, 'Y2EiaY', 1);
INSERT INTO UCEBNA (ID, KAPACITA, NAZEV, BUDOVA, LABORATOR) VALUES (UCEBNA_id_SEQ.nextval, 17, 'S4AEFK0k5T2x', NULL, 1);
INSERT INTO UCEBNA (ID, KAPACITA, NAZEV, BUDOVA, LABORATOR) VALUES (UCEBNA_id_SEQ.nextval, NULL, '2BON1J1f', 'VhBO8kfN8ZQqF', 1);
INSERT INTO UCEBNA (ID, KAPACITA, NAZEV, BUDOVA, LABORATOR) VALUES (UCEBNA_id_SEQ.nextval, -1, '8zWtpCzHyyvWCy', 'zOEvCvlXgt4qg', 1);

-- Porušení netriviálních integritiních omezení tabulky REL_RA_UCEBNA
INSERT INTO REL_RA_UCEBNA (ROZVRHOVA_AKCE_ID, UCEBNA_ID) VALUES (212, 35);
INSERT INTO REL_RA_UCEBNA (ROZVRHOVA_AKCE_ID, UCEBNA_ID) VALUES (696, 32);

-- Porušení netriviálních integritiních omezení tabulky ROZVRHOVA_AKCE
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('8:15:46', 'HH24:MI:SS'), TO_DATE('10.1.21', 'DD.MM.YY'), 2, 101 , 111, 22, 12);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('11:15:21', 'HH24:MI:SS'), NULL, 2, 96 , 129, 34, 6);
INSERT INTO ROZVRHOVA_AKCE (ID, CAS, DATUM, POCETHODIN, UCITEL_ID, KATEGORIE_ID, PREDMET_ID, POCETSTUDENTU) VALUES (ROZVRHOVA_AKCE_id_SEQ.nextval, TO_TIMESTAMP('11:22:50', 'HH24:MI:SS'), TO_DATE('15.3.20', 'DD.MM.YY'), 2, 66 , 155, 58, 23);
